version: '3'
services:
  dbt-bq-dtc:
    build:
      context: .
      target: dbt-bigquery
    image: dbt
    volumes:
      - .:/usr/app
      - ~/.dbt/:/root/.dbt/
      - ~/.google/credentials/google_credentials.json:/.google/credentials/google_credentials.json
    network_mode: host

  piperider:
    image: infuseai/piperider:v0.1.3.14
