bq-dbt-workshop:
  outputs:
    dev:
      dataset: taxi_rides_ny
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: europe-west6
      method: service-account
      priority: interactive
      project: dtc-de-375918
      threads: 4
      timeout_seconds: 600
      type: bigquery
  target: dev
  